# run: conda env create --file environment.yml
name: HSI
dependencies:
  - python=3.6
  - nb_conda
  - cvxopt==1.1.9
  - cycler==0.10.0
  - Cython==0.27.3
  - matplotlib==2.1.1
  - numpy==1.14.0
  - scikit-learn==0.19.1
  - scipy==1.0.0
  - qtconsole==4.3.1
  - simplegeneric==0.8.1
  - pyparsing==2.2.0
  - html5lib==1.0.1
  - pytz==2017.3
  - pip
  - pip:
    - pysptools==0.14.2
    - quadprog==0.1.6
channels:
  - defaults
  - conda-forge
  - bioconda
